name: Parametric Curve Fitting for Trend Analysis
description: Parametric Curve Fitting for Trend Analysis
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2021-01-21"
api_version: 1



tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: cml/install_dependencies.py
    arguments: None
    short_summary: Job to install dependencies.
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: install_deps
    short_summary: Running job to dependencies job.
    long_summary: >-
      Running the job to install dependencies.

  - type: create_job
    name: Load data and train model
    entity_label: train_model
    script: cml/train_models.py
    arguments: None
    short_summary: Job to load data and train curve fitting models.
    cpu: 2
    memory: 10
    environment:
      TASK_TYPE: CREATE/RUN_JOB
    kernel: python3

  - type: run_job
    entity_label: train_model
    short_summary: Running job to load data and train curve fitting models.
    long_summary: >-
      Running job to load data and curve fitting train models.
      
  - type: create_model
    name: Curve Fitting Model Endpoint
    entity_label: curvefit_model
    description: This model api endpoint   predicts trends
    short_summary: Create the curve fitting api endpoint
    access_key_environment_variable: SHTM_ACCESS_KEY
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Curve Fitting Model Endpoint
    entity_label: curvefit_model
    comment: Build curve fitting model
    examples:
      - request: {"feature" : "US,DCA,BOS,1,16"}
        response: 1
    target_file_path: cml/model_get_trend.py
    target_function_name: predict
    kernel: python3
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: deploy_model
    name: curvefit_model
    entity_label: curvefit_model
    cpu: 1
    gpu: 0
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: start_application
    name: Application to serve UI
    subdomain: curvefitting
    script: app/backend/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    kernel: python3
